language: node_js

node_js:
  - stable

deploy:
  provider: npm
  on:
    tags: true
  email:
    secure: xz1OZaMTD87IgHcDNzLLiLEXJ/cj/5OcaaO8YuUafCG+Tvgr53t3cSEJdpDe/2LtVlevYP8kDUTG6e6AirR/VEZe01Y4SwGqr99bNclu14+5rDu7ygzRQLcbfBk9QubL4XjvN7vWbPio/g5isakafZB8gLLHkqAhlTGUsD3AmYzzc/mYitbXivzwnQSbOGDfx2D0NilBHGuUpU46q7dWZ51EB/LvkynUaWqdSEr0IEOXuxfjmW5R2AjuSLE1acKA2bL+w8hM8j494nX7764FxbtRiVtJeXgUqKM8jpyob3T/abcCLCMkaMYNL1wgM30wL39W5gLpSaFVQLgyMw7mlr30TD5nT9upV7aXqMJlGrFnxV+ndW+sxW/a5lf7vThzR+gWtGPJD0VotBLqDps12X3aVDH23Q2vJRWvIv/JXdHNldr47oXE/u64v0TM2D1gYm/tAULFIi5fJjgn2+oPR/UavrAlX9iIGjsdnfDYRAftc4kz5XRv1/GJnbUYL1aIqkY9JUhROXTNyWtXPrXGfFiPknSZoP72nWbHG1RrmANOVsK5HzSrJ3pQH5MjsqXUH0n1N77PxWviM87L4p5CHZGVYs7JYgBe3QByvhWprlgyvuVp3kGxbSUvZizFl4KL5kUmr33fPgHWuLL1IoQLnVioSQ05W2lRcajSA8fgM5w=
  api_key:
    secure: ffprsnnF1RbwsaRtUlrkKp794a28hhSC7g0M47gxBZSOv5IbxqeJUukFv+qkeB7UI6sS3UbZNNAU0d6wrh1TnMZ0Uxwr6Rb9fg/UpgtP4ACnWd4ZQ1HlmAYLOCbFP1PJ8k93CKfx87NGP1wazHITfz25nditwfYnA0+PW4NXXwqWeqRvHeXKHXvGB2Losy73icrq1KUy+EJ9/pG69EpD827KLwhZYUMWMohxB37p+moRizhUezC0/Dd5vuu8k1lPX4Xl78N5aQE3GpL8A7BCfUNirpmOijnXcYxsMqiY0F44PPXPfY6qrDcqSOcRq96Lu8ofn85wf1TBCTnCXkd4jdss1CeQ1VXFImoHKF2yVHMzeciqVqD1lV5V7URQw4bIgGf6BAQ90cFmtxmBmV6PBLXktXdqNZpwwK/oYVqT8wTSVIkoy/Z1EpO0N8/3FcnIOwTIqfzLixm2MFMf3yXM08XhcSFuniolygnPbjLLzZ8gsAjOdUByyoS9cPxTAOjvDGvSqk7FckHDPTPHJ7xXqHzFM5xBj2rzk5l1oPNEpCuJ1BF/Vtpy/0A6KpDoDxPXdGZFx82BKz1PZP0g/+DFUqcZ49uFV54vpHC+GTG0T5UDFf1J+AmMKzIRdrLpFLiPkrvNdc8/BE+Es2UZOekPTRib0RfjX+3nL7/LiFUh0So=
  skip_cleanup: true
